service: spotify-samples

provider:
  name: aws
  runtime: python3.8
  stage: dev
  region: eu-central-1

plugins:
  - serverless-python-requirements
  - serverless-wsgi

functions:
  app:
    handler: wsgi_handler.handler
    timeout: 30
    events:
      - http: ANY /
      - http: 'ANY {proxy+}'

custom:
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: false
